### ISSUE TITLE
Manual install for firefox?

### ISSUE THREAD

**Issue by jason-s-yu** [califernication/lichessAnalysis#2]
Hey! is it possible to install this manually on Firefox? Looks like the "Install add-on from file..." option requires a `.xpi`, `.jar`, or `.zip`

**Comment by zeraye** [comment]
Same extension but developed for firefox https://github.com/zeraye/chess-analysis-firefox-extension

**Comment by califernication** [comment]
Yes! You can compress the downloaded file (if it does not come as a .zip) in releases from this repo and upload to the extensions page of Firefox.
