### ISSUE TITLE
Plugin recently broken

### ISSUE THREAD

**Issue by alain-picard** [califernication/lichessAnalysis#3]
Perhaps chess.com changed something, and it inadventantly broke the extension?  I no longer see the "analyze on lichess" button on my chess.com pages.

**Comment by MrDiamondDog** [comment]
+1

**Comment by Xoroxa** [comment]
I fixed this and added a pull request. Hopefully the person who made this actually checks this and can merge it.

**Comment by MarvashMagalli** [comment]
> I fixed this and added a pull request. Hopefully the person who made this actually checks this and can merge it.

stupid question, is there any way to use this fix already "unofficially", or do we have to wait for the person who made this?

**Comment by califernication** [comment]
Hey @Xoroxa. Thanks for looking into it. I'll review the pull request in the coming days and make a decision as soon as possible.

**Comment by califernication** [comment]
@Xoroxa's pull request has been merged. I submitted the updated file to the Chrome Web Store. It's gonna take some time to be reviewed, but it should show up in place of the current version (1.1 -> 1.2) at some point.
